{
    'REQUEST_METHOD': 'GET',
    'QUERY_STRING': '',
    'SCRIPT_NAME': '',
    'PATH_INFO': '/community/view/0v6r7jBK5LNHnr92RcGL/',
    'wsgi.multithread': True,
    'wsgi.multiprocess': True,
    'REMOTE_ADDR': '127.0.0.1',
    'REMOTE_HOST': '127.0.0.1',
    'REMOTE_PORT': 8981,
    'SERVER_NAME': '127.0.0.1',
    'SERVER_PORT': '8000',
    'HTTP_HOST': '127.0.0.1:8000',
    'HTTP_CONNECTION': 'keep-alive',
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36',
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'HTTP_SEC_FETCH_SITE': 'same-origin',
    'HTTP_SEC_FETCH_MODE': 'navigate',
    'HTTP_SEC_FETCH_USER': '?1',
    'HTTP_SEC_FETCH_DEST': 'document',
    'HTTP_SEC_CH_UA': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'HTTP_SEC_CH_UA_MOBILE': '?0',
    'HTTP_SEC_CH_UA_PLATFORM': '"Windows"',
    'HTTP_REFERER': 'http://127.0.0.1:8000/community/',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'HTTP_COOKIE': 'csrftoken=jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ; sessionid=mq6ht454is8nc5ecn632hyy71bt4h9av',
    'CSRF_COOKIE': 'jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ'
}
{
    'REQUEST_METHOD': 'GET',
    'QUERY_STRING': '',
    'SCRIPT_NAME': '',
    'PATH_INFO': '/community/view/0v6r7jBK5LNHnr92RcGL/',
    'wsgi.multithread': True,
    'wsgi.multiprocess': True,
    'REMOTE_ADDR': '127.0.0.1',
    'REMOTE_HOST': '127.0.0.1',
    'REMOTE_PORT': 9564,
    'SERVER_NAME': '127.0.0.1',
    'SERVER_PORT': '8000',
    'HTTP_HOST': '127.0.0.1:8000',
    'HTTP_CONNECTION': 'keep-alive',
    'HTTP_CACHE_CONTROL': 'max-age=0',
    'HTTP_SEC_CH_UA': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'HTTP_SEC_CH_UA_MOBILE': '?0',
    'HTTP_SEC_CH_UA_PLATFORM': '"Windows"',
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36',
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'HTTP_SEC_FETCH_SITE': 'same-origin',
    'HTTP_SEC_FETCH_MODE': 'navigate',
    'HTTP_SEC_FETCH_USER': '?1',
    'HTTP_SEC_FETCH_DEST': 'document',
    'HTTP_REFERER': 'http://127.0.0.1:8000/community/',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'HTTP_COOKIE': 'csrftoken=jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ; sessionid=mq6ht454is8nc5ecn632hyy71bt4h9av',
    'CSRF_COOKIE': 'jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ'
}

{
    'REQUEST_METHOD': 'GET',
    'QUERY_STRING': '',
    'SCRIPT_NAME': '',
    'PATH_INFO': '/community/view/0v6r7jBK5LNHnr92RcGL/',
    'wsgi.multithread': True,
    'wsgi.multiprocess': True,
    'REMOTE_ADDR': '127.0.0.1',
    'REMOTE_HOST': '127.0.0.1',
    'REMOTE_PORT': 14309,
    'SERVER_NAME': '127.0.0.1',
    'SERVER_PORT': '8000',
    'HTTP_HOST': '127.0.0.1:8000',
    'HTTP_CONNECTION': 'keep-alive',
    'HTTP_SEC_CH_UA': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'HTTP_SEC_CH_UA_MOBILE': '?0',
    'HTTP_SEC_CH_UA_PLATFORM': '"Windows"',
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36',
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'HTTP_SEC_FETCH_SITE': 'none',
    'HTTP_SEC_FETCH_MODE': 'navigate',
    'HTTP_SEC_FETCH_USER': '?1',
    'HTTP_SEC_FETCH_DEST': 'document',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'HTTP_COOKIE': 'csrftoken=jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ; sessionid=mq6ht454is8nc5ecn632hyy71bt4h9av',
    'CSRF_COOKIE': 'jQyEKkge8YbFcF88J8hy2LRX2SZjDPcBBUd1zKnbmsfyVvoWqFBLg98Tuy1JMhlJ'
}